name: GitHub Actions pipeline for Learning Go code examples
on:
  push:
    branches:
    - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.1'
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run unit tests on Chapter 1 code examples
      run: |
        cd ch1/
        make test
        cd ..
    - name: Run unit tests on Chapter 2 code examples
      run: |
        cd ch2/
        make test
        cd ..
    - name: Run unit tests on Chapter 3 code examples
      run: |
        cd ch3/
        make test
        cd ..
